const LANGUAGES=[{code:"auto",name:"Auto detect"},{code:"en",name:"English"},{code:"zh",name:"Chinese Simplified"},{code:"es",name:"Spanish"},{code:"az",name:"Azerbaijani"},{code:"tr",name:"Turkish"},{code:"ru",name:"Russian"},{code:"fr",name:"French"},{code:"de",name:"German"},{code:"it",name:"Italian"},{code:"pt",name:"Portuguese"},{code:"ar",name:"Arabic"},{code:"ja",name:"Japanese"},{code:"ko",name:"Korean"}];
const PHRASES=[
["Taxi", "Please take me to this address.", "请带我去这个地址。", "Show the address after this.", "qǐng dài wǒ qù zhè ge dì zhǐ."],
["Taxi", "Please use the meter.", "请打表。", "Useful in taxis.", "qǐng dǎ biǎo."],
["Taxi", "Can you wait here for five minutes?", "你能在这里等我五分钟吗？", "Short waiting request.", "nǐ néng zài zhè lǐ děng wǒ wǔ fēn zhōng ma?"],
["Hotel", "I have a reservation under this name.", "我用这个名字预订了房间。", "Show your name/passport.", "wǒ yòng zhè ge míng zi yù dìng le fáng jiān."],
["Hotel", "Can I check in early?", "我可以提前入住吗？", "Hotel check-in.", "wǒ kě yǐ tí qián rù zhù ma?"],
["Hotel", "Can you write the address in Chinese?", "你能用中文写一下地址吗？", "Very useful for taxis.", "nǐ néng yòng zhōng wén xiě yí xià dì zhǐ ma?"],
["Restaurant", "Do you have an English menu?", "你们有英文菜单吗？", "Restaurant basic.", "nǐ men yǒu yīng wén cài dān ma?"],
["Restaurant", "I do not eat pork.", "我不吃猪肉。", "Dietary need.", "wǒ bù chī zhū ròu."],
["Restaurant", "Can I have the bill, please?", "请给我账单。", "Paying.", "qǐng gěi wǒ zhàng dān."],
["Payments", "Can I pay by card?", "我可以刷卡吗？", "Card payment.", "wǒ kě yǐ shuā kǎ ma?"],
["Payments", "Can I pay with cash?", "我可以付现金吗？", "Cash payment.", "wǒ kě yǐ fù xiàn jīn ma?"],
["Payments", "The payment did not go through.", "支付没有成功。", "Payment problem.", "zhī fù méi yǒu chéng gōng."],
["Directions", "Where is the nearest metro station?", "最近的地铁站在哪里？", "Navigation.", "zuì jìn de dì tiě zhàn zài nǎ lǐ?"],
["Directions", "Is it far from here?", "离这里远吗？", "Distance.", "lí zhè lǐ yuǎn ma?"],
["Directions", "Please show me on the map.", "请在地图上给我看。", "Useful when speaking fails.", "qǐng zài dì tú shàng gěi wǒ kàn."],
["Shopping", "How much is this?", "这个多少钱？", "Price.", "zhè ge duō shǎo qián?"],
["Shopping", "Do you have a larger size?", "你们有大一点的尺码吗？", "Clothes/shoes.", "nǐ men yǒu dà yì diǎn de chǐ mǎ ma?"],
["Shopping", "Can you give me a receipt?", "可以给我收据吗？", "Receipt.", "kě yǐ gěi wǒ shōu jù ma?"],
["Emergency", "I need help.", "我需要帮助。", "Emergency.", "wǒ xū yào bāng zhù."],
["Emergency", "Please call the police.", "请报警。", "Emergency.", "qǐng bào jǐng."],
["Emergency", "I need a doctor.", "我需要医生。", "Medical.", "wǒ xū yào yī shēng."],
["Medical", "I am allergic to this.", "我对这个过敏。", "Allergy.", "wǒ duì zhè ge guò mǐn."],
["Medical", "I feel sick.", "我感觉不舒服。", "Health.", "wǒ gǎn jué bù shū fu."],
["Medical", "Where is the nearest pharmacy?", "最近的药店在哪里？", "Pharmacy.", "zuì jìn de yào diàn zài nǎ lǐ?"],
["General", "Can you speak more slowly?", "你可以说慢一点吗？", "Conversation.", "nǐ kě yǐ shuō màn yì diǎn ma?"],
["General", "Please write it down.", "请写下来。", "When pronunciation is hard.", "qǐng xiě xià lái."],
["General", "I do not understand.", "我不明白。", "Basic.", "wǒ bù míng bai."]
].map(([category,text,zh,note,pinyin])=>({category,text,zh,note,pinyin}));
const $=id=>document.getElementById(id);
const sourceLang=$("sourceLang"),targetLang=$("targetLang"),inputText=$("inputText"),outputText=$("outputText"),pinyinBox=$("pinyinBox"),pinyinText=$("pinyinText"),engineSelect=$("engineSelect"),engineStatus=$("engineStatus"),settingsPanel=$("settingsPanel"),libreEndpointInput=$("libreEndpointInput"),libreApiKeyInput=$("libreApiKeyInput"),phraseCategorySelect=$("phraseCategorySelect"),phraseGrid=$("phraseGrid"),recentList=$("recentList"),savedList=$("savedList"),conversationList=$("conversationList"),largeModal=$("largeModal"),largeText=$("largeText"),themeToggle=$("themeToggle");
const presetButtons=[...document.querySelectorAll(".preset")],tabButtons=[...document.querySelectorAll(".tab-button")];
let recentTranslations=JSON.parse(localStorage.getItem("wayspeakRecent")||"[]"),savedPhrases=JSON.parse(localStorage.getItem("wayspeakSaved")||"[]"),conversationCards=JSON.parse(localStorage.getItem("wayspeakConversation")||"[]"),theme=localStorage.getItem("wayspeakTheme")||"light";
function populateLanguages(){sourceLang.innerHTML=LANGUAGES.map(l=>`<option value="${l.code}">${l.name}</option>`).join("");targetLang.innerHTML=LANGUAGES.filter(l=>l.code!=="auto").map(l=>`<option value="${l.code}">${l.name}</option>`).join("");sourceLang.value=localStorage.getItem("wayspeakSource")||"en";targetLang.value=localStorage.getItem("wayspeakTarget")||"zh"}
function checkEngineSupport(){const has=!!(window.Translator||window.translation?.createTranslator);engineStatus.textContent=has?"Browser translation may be available. MyMemory is also available as a free fallback.":"Browser translation is not available here. MyMemory Free API is selected as the live fallback.";engineSelect.value=localStorage.getItem("wayspeakEngine")||(has?"browser":"mymemory")}

const PINYIN_MAP={"你":"nǐ","好":"hǎo","请":"qǐng","带":"dài","我":"wǒ","去":"qù","这":"zhè","个":"ge","地":"dì","址":"zhǐ","打":"dǎ","表":"biǎo","能":"néng","在":"zài","里":"lǐ","等":"děng","五":"wǔ","分":"fēn","钟":"zhōng","吗":"ma","用":"yòng","名":"míng","字":"zi","预":"yù","订":"dìng","了":"le","房":"fáng","间":"jiān","可":"kě","以":"yǐ","提":"tí","前":"qián","入":"rù","住":"zhù","中":"zhōng","文":"wén","写":"xiě","一":"yí","下":"xià","们":"men","有":"yǒu","英":"yīng","菜":"cài","单":"dān","不":"bù","吃":"chī","猪":"zhū","肉":"ròu","给":"gěi","账":"zhàng","刷":"shuā","卡":"kǎ","付":"fù","现":"xiàn","金":"jīn","支":"zhī","没":"méi","成":"chéng","功":"gōng","最":"zuì","近":"jìn","的":"de","铁":"tiě","站":"zhàn","哪":"nǎ","离":"lí","远":"yuǎn","图":"tú","上":"shàng","看":"kàn","多":"duō","少":"shǎo","钱":"qián","大":"dà","点":"diǎn","尺":"chǐ","码":"mǎ","收":"shōu","据":"jù","需":"xū","要":"yào","帮":"bāng","助":"zhù","报":"bào","警":"jǐng","医":"yī","生":"shēng","对":"duì","过":"guò","敏":"mǐn","感":"gǎn","觉":"jué","舒":"shū","服":"fu","药":"yào","店":"diàn","说":"shuō","慢":"màn","明":"míng","白":"bai","谢":"xiè","再":"zài","见":"jiàn","是":"shì","否":"fǒu","人":"rén","水":"shuǐ","厕":"cè","所":"suǒ","机":"jī","场":"chǎng","火":"huǒ","车":"chē","酒":"jiǔ","急":"jí","救":"jiù"};
function containsChinese(text){return /[\u3400-\u9FFF]/.test(text||"")}
function phrasePinyinForChinese(text){const match=PHRASES.find(p=>p.zh===text.trim());return match?.pinyin||""}
function generatePinyin(text){const exact=phrasePinyinForChinese(text);if(exact)return exact;return Array.from(text).map(ch=>{if(PINYIN_MAP[ch])return PINYIN_MAP[ch];if(/[，。？！、,.?!]/.test(ch))return ch;if(/\s/.test(ch))return " ";return /[\u3400-\u9FFF]/.test(ch)?"?":ch}).join(" ").replace(/\s+([，。？！、,.?!])/g,"$1").replace(/\s+/g," ").trim()}
function updatePinyin(){const text=outputText.textContent.trim();if(containsChinese(text)){const py=generatePinyin(text);pinyinText.textContent=py.includes("?")?`${py}  ·  rough pinyin`:py;pinyinBox.hidden=false}else{pinyinBox.hidden=true;pinyinText.textContent=""}}

async function translateText(){const text=inputText.value.trim();if(!text){outputText.textContent="Type something first.";return}outputText.textContent="Translating...";try{let t="";if(engineSelect.value==="browser")t=await translateWithBrowser(text);else if(engineSelect.value==="mymemory")t=await translateWithMyMemory(text);else if(engineSelect.value==="libre")t=await translateWithLibre(text);else t=findPhrasebookTranslation(text);outputText.textContent=t||"No translation available from this engine.";updatePinyin();saveRecent(text,outputText.textContent)}catch(e){console.error(e);outputText.textContent="Translation failed. Try another engine or use the phrasebook.";updatePinyin()}}
async function translateWithBrowser(text){const from=sourceLang.value==="auto"?"en":sourceLang.value,to=targetLang.value;if(window.Translator?.create){const tr=await window.Translator.create({sourceLanguage:from,targetLanguage:to});return await tr.translate(text)}if(window.translation?.createTranslator){const tr=await window.translation.createTranslator({sourceLanguage:from,targetLanguage:to});return await tr.translate(text)}throw new Error("Browser Translator API unavailable.")}

async function translateWithMyMemory(text){
  const source = sourceLang.value === "auto" ? "en" : sourceLang.value;
  const target = targetLang.value;
  const langpair = `${source}|${target}`;
  const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${encodeURIComponent(langpair)}`;
  const response = await fetch(url);
  if(!response.ok) throw new Error("MyMemory request failed.");
  const data = await response.json();
  if(data.responseStatus && Number(data.responseStatus) >= 400) {
    throw new Error(data.responseDetails || "MyMemory translation failed.");
  }
  return data.responseData?.translatedText || "";
}

async function translateWithLibre(text){const endpoint=localStorage.getItem("wayspeakLibreEndpoint")||"",key=localStorage.getItem("wayspeakLibreApiKey")||"";if(!endpoint)throw new Error("LibreTranslate endpoint missing.");const body={q:text,source:sourceLang.value==="auto"?"auto":sourceLang.value,target:targetLang.value,format:"text"};if(key)body.api_key=key;const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error("LibreTranslate request failed.");const d=await r.json();return d.translatedText||""}
function findPhrasebookTranslation(text){const n=text.trim().toLowerCase(),m=PHRASES.find(p=>p.text.toLowerCase()===n||p.zh.toLowerCase()===n);if(!m)return"Phrasebook mode only translates built-in travel phrases. Try selecting a phrase below.";if(targetLang.value==="zh")return m.zh;if(sourceLang.value==="zh")return m.text;return m.zh}
function saveRecent(input,output){recentTranslations=recentTranslations.filter(i=>i.input!==input||i.output!==output);recentTranslations.unshift({input,output,from:sourceLang.value,to:targetLang.value,date:new Date().toISOString()});recentTranslations=recentTranslations.slice(0,30);localStorage.setItem("wayspeakRecent",JSON.stringify(recentTranslations));renderRecent()}
function saveCurrentPhrase(){const input=inputText.value.trim(),output=outputText.textContent.trim();if(!input||!output||output==="Your translation will appear here.")return;savedPhrases=savedPhrases.filter(i=>i.input!==input||i.output!==output);savedPhrases.unshift({input,output,from:sourceLang.value,to:targetLang.value,date:new Date().toISOString()});localStorage.setItem("wayspeakSaved",JSON.stringify(savedPhrases));renderSaved()}
function addConversationCard(){const output=outputText.textContent.trim(),input=inputText.value.trim();if(!output||output==="Your translation will appear here.")return;conversationCards.unshift({input,output,from:sourceLang.value,to:targetLang.value,date:new Date().toISOString()});conversationCards=conversationCards.slice(0,20);localStorage.setItem("wayspeakConversation",JSON.stringify(conversationCards));renderConversation()}
function renderPhrasebook(){const old=phraseCategorySelect.value||"All",cats=["All",...new Set(PHRASES.map(p=>p.category))];phraseCategorySelect.innerHTML=cats.map(c=>`<option value="${c}">${c}</option>`).join("");phraseCategorySelect.value=cats.includes(old)?old:"All";const arr=phraseCategorySelect.value==="All"?PHRASES:PHRASES.filter(p=>p.category===phraseCategorySelect.value);phraseGrid.innerHTML=arr.map(p=>`<article class="phrase-card" data-i="${PHRASES.indexOf(p)}"><span class="badge">${escapeHTML(p.category)}</span><strong>${escapeHTML(p.text)}</strong><span>${escapeHTML(p.zh)}</span><span>${escapeHTML(p.pinyin)}</span><span>${escapeHTML(p.note)}</span></article>`).join("");phraseGrid.querySelectorAll(".phrase-card").forEach(c=>c.onclick=()=>loadPhrase(PHRASES[+c.dataset.i]))}
function loadPhrase(p){if(targetLang.value==="zh"){inputText.value=p.text;outputText.textContent=p.zh;sourceLang.value="en";targetLang.value="zh"}else if(sourceLang.value==="zh"){inputText.value=p.zh;outputText.textContent=p.text}else{inputText.value=p.text;outputText.textContent=p.zh;targetLang.value="zh"}updatePinyin();saveRecent(inputText.value,outputText.textContent)}
function renderStackItem(i,idx){return`<article class="stack-item" data-i="${idx}"><span class="badge">${escapeHTML(i.from)} → ${escapeHTML(i.to)}</span><strong>${escapeHTML(i.input)}</strong><span>${escapeHTML(i.output)}</span></article>`}
function bindStack(el,arr){el.querySelectorAll(".stack-item").forEach(c=>c.onclick=()=>{const i=arr[+c.dataset.i];inputText.value=i.input;outputText.textContent=i.output;updatePinyin();sourceLang.value=i.from;targetLang.value=i.to})}
function renderRecent(){recentList.innerHTML=recentTranslations.length?recentTranslations.map(renderStackItem).join(""):`<div class="phrase-card"><strong>No recent translations yet.</strong><span>Translate something and it will appear here.</span></div>`;bindStack(recentList,recentTranslations)}
function renderSaved(){savedList.innerHTML=savedPhrases.length?savedPhrases.map(renderStackItem).join(""):`<div class="phrase-card"><strong>No saved phrases yet.</strong><span>Save useful translations for later.</span></div>`;bindStack(savedList,savedPhrases)}
function renderConversation(){conversationList.innerHTML=conversationCards.length?conversationCards.map(i=>`<article class="conversation-card"><div class="small">${escapeHTML(i.from)} → ${escapeHTML(i.to)}</div><div class="big">${escapeHTML(i.output)}</div></article>`).join(""):`<div class="phrase-card"><strong>No conversation cards yet.</strong><span>Add the current translation to show it quickly later.</span></div>`}
function setTab(tab){tabButtons.forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));["phrasebook","recent","saved","conversation"].forEach(k=>$(k+"Tab").hidden=k!==tab)}
function swapLanguages(){if(sourceLang.value==="auto"){sourceLang.value=targetLang.value;targetLang.value="en"}else{[sourceLang.value,targetLang.value]=[targetLang.value,sourceLang.value]}const old=inputText.value;inputText.value=outputText.textContent==="Your translation will appear here."?"":outputText.textContent;outputText.textContent=old||"Your translation will appear here.";updatePinyin();saveLang()}
function saveLang(){localStorage.setItem("wayspeakSource",sourceLang.value);localStorage.setItem("wayspeakTarget",targetLang.value)}
function applyPreset(b){presetButtons.forEach(x=>x.classList.remove("active"));b.classList.add("active");sourceLang.value=b.dataset.source;targetLang.value=b.dataset.target;saveLang()}
async function copyText(t){if(t)await navigator.clipboard.writeText(t)}
function showLarge(){const t=outputText.textContent.trim();if(!t||t==="Your translation will appear here.")return;largeText.textContent=pinyinText.textContent?`${t}\n\n${pinyinText.textContent}`:t;largeModal.hidden=false}
function clearInput(){inputText.value="";outputText.textContent="Your translation will appear here.";updatePinyin()}
function saveSettings(){localStorage.setItem("wayspeakLibreEndpoint",libreEndpointInput.value.trim());localStorage.setItem("wayspeakLibreApiKey",libreApiKeyInput.value.trim());localStorage.setItem("wayspeakEngine",engineSelect.value);settingsPanel.hidden=true}
function loadSettings(){libreEndpointInput.value=localStorage.getItem("wayspeakLibreEndpoint")||"";libreApiKeyInput.value=localStorage.getItem("wayspeakLibreApiKey")||""}
function applyTheme(t){document.body.classList.toggle("dark",t==="dark");themeToggle.textContent=t==="dark"?"Light Mode":"Dark Mode";localStorage.setItem("wayspeakTheme",t);theme=t}
function escapeHTML(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
$("translateButton").onclick=translateText;$("swapButton").onclick=swapLanguages;$("clearButton").onclick=clearInput;$("copyInputButton").onclick=()=>copyText(inputText.value);$("copyOutputButton").onclick=()=>copyText(outputText.textContent);$("copyPinyinButton").onclick=()=>copyText(pinyinText.textContent);$("savePhraseButton").onclick=saveCurrentPhrase;$("showLargeButton").onclick=showLarge;$("closeLargeButton").onclick=()=>largeModal.hidden=true;themeToggle.onclick=()=>applyTheme(theme==="dark"?"light":"dark");sourceLang.onchange=saveLang;targetLang.onchange=saveLang;engineSelect.onchange=()=>localStorage.setItem("wayspeakEngine",engineSelect.value);$("settingsButton").onclick=()=>settingsPanel.hidden=!settingsPanel.hidden;$("saveSettingsButton").onclick=saveSettings;phraseCategorySelect.onchange=renderPhrasebook;$("clearRecentButton").onclick=()=>{recentTranslations=[];localStorage.setItem("wayspeakRecent","[]");renderRecent()};$("clearSavedButton").onclick=()=>{savedPhrases=[];localStorage.setItem("wayspeakSaved","[]");renderSaved()};$("addConversationButton").onclick=addConversationCard;presetButtons.forEach(b=>b.onclick=()=>applyPreset(b));tabButtons.forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.warn));
populateLanguages();checkEngineSupport();loadSettings();applyTheme(theme);renderPhrasebook();renderRecent();renderSaved();renderConversation();
